### ISSUE TITLE
How to get correct version for composer?

### ISSUE THREAD

**Issue by nitinthewiz** [aaronpk/QuartzDB#3]
Hey Aaron,

I've started using Quartz for a project. More on this later.

But I'm running into some trouble. There's a fix, specifically, d0273a08181cffd91343ba788ff234fbd9daffa6, which I need because there's a newline being added to new files.

My composer.json is simply - 

{
	"name": "nitinthewiz/TheLiveBlog",
	"require": {
        "p3k/quartz-db": "0.1.*"
    }
}

and the corresponding composer.lock is -

"packages": [
        {
            "name": "p3k/quartz-db",
            "version": "0.1.4",
            "source": {
                "type": "git",
                "url": "https://github.com/aaronpk/QuartzDB.git",
                "reference": "665f90e08025cc670734fb25cb441363b22e3fa3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/aaronpk/QuartzDB/zipball/665f90e08025cc670734fb25cb441363b22e3fa3",
                "reference": "665f90e08025cc670734fb25cb441363b22e3fa3",
                "shasum": ""
            },

But when I look at my Compass installation, the composer.lock is -

"name": "p3k/quartz-db",
            "version": "0.1.1",
            "source": {
                "type": "git",
                "url": "https://github.com/aaronpk/QuartzDB.git",
                "reference": "d0273a08181cffd91343ba788ff234fbd9daffa6"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/aaronpk/QuartzDB/zipball/d0273a08181cffd91343ba788ff234fbd9daffa6",
                "reference": "d0273a08181cffd91343ba788ff234fbd9daffa6",
                "shasum": ""
            },

which includes exactly the reference I need - d0273a08181cffd91343ba788ff234fbd9daffa6

My composer is picking up 0.1.4, but even that doesn't seem to have the correct fix in place.

This is a composer question, mainly, but can you tell me how I'm supposed to pull the right changes? Did you build Compass using git and then use composer lock to lock it to that fix?

**Comment by nitinthewiz** [comment]
Ok, the reference number is wrong. But the piece of code I'm looking for is this. I've hardcoded it for now, but I'd like to know if there's a solution -

if($this->_fileWasJustCreated) {
      $this->_fileWasJustCreated = false;
      $newline = '';
    } else {
      $newline = "\n";
    }

**Comment by nitinthewiz** [comment]
What's happening is that when I create a new entry or when I import a large amount of data into the database the first time, every entry gets created with a blank newline at the end. When I go to read it, I get an error, "Line was empty". This error doesn't occur in Compass, and the newline at the end also doesn't occur in Compass, so I can only assume that the right fixes are in place in Compass' composer.lock file.

**Comment by aaronpk** [comment]
I'm confused about the exact problem you're having.

If Compass' `composer.lock` is referencing 0.1.1, try running `composer update p3k/quartz-db` to get it to update that version, or change your `composer.json` to reference `>=1.1.4`. 

It sounds like that's the root of the problem, as that fix was in version 1.1.3.

**Comment by nitinthewiz** [comment]
hmmm. I'll try to specifically reference 1.1.4 👍
